// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnbVaIcOIOmpyovdZr4QulrSbsHpFsOr8',
    appId: '1:444199715264:web:adfdc3a9a9036005eb0825',
    messagingSenderId: '444199715264',
    projectId: 'app-scanner-cbef8',
    authDomain: 'app-scanner-cbef8.firebaseapp.com',
    storageBucket: 'app-scanner-cbef8.firebasestorage.app',
    measurementId: 'G-WVZHCC2GDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhk1i85E0PC5E_mrifqRqjZzw8GDKtHHs',
    appId: '1:444199715264:android:435a881086231daceb0825',
    messagingSenderId: '444199715264',
    projectId: 'app-scanner-cbef8',
    storageBucket: 'app-scanner-cbef8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBACKmw8Z0-w9dqmNGkdZZKrtT1btXJ4gA',
    appId: '1:444199715264:ios:fada172b1605a6ceeb0825',
    messagingSenderId: '444199715264',
    projectId: 'app-scanner-cbef8',
    storageBucket: 'app-scanner-cbef8.firebasestorage.app',
    iosBundleId: 'com.example.appScanner',
  );
}
